title: Oak
description: ðŸŒ³ Measure outdoor distance between 2 keychain holders ðŸ”‘
url: "https://hutscape.com/oak"
markdown: kramdown
permalink: /:title
youtube: https://www.youtube.com/user/sweska/videos
github:
  repository_url: https://github.com/hutscape/oak
  raw_content_url: https://raw.githubusercontent.com/hutscape/oak/master
exclude: ["datasheets", "Gemfile", "Gemfile.lock", "contributing.md", "Makefile", "readme.md", "scripts", "firmware"]
include: ["_data"]
